[package]
name = "sorts"
version = "0.2.0"
authors = ["Olav de Haas <o.n.dehaas@student.tudelft.nl>"]
description = "A collection of sorting algorithms"
keywords = ["sort", "sorting", "library"]
categories = ["algorithms"]
license = "MIT"

[dependencies]

[dev-dependencies]
rand = "0.5"
